### PR TITLE
chore(git-setup): update SSH creation and connection process to GitLab

### PR DESCRIPTION
**Pull request by Ace0009**
I made some minor changes to `chalmers-gitlab.md`

### CODE REVIEW

**Comment by sattlerc** [comment]
Thanks! We didn't notice that the link to SSH keys on the Chalmers GitLab user profile was outdated. I fixed this now.

I'm not convinced about these instructions:
>   - For Mac, run: `tr -d '\n' < ~/.ssh/id_ed25519.pub | pbcopy`.
>   - For Windows (in Git Bash), run: `cat ~/.ssh/id_ed25519.pub | clip`.
>   - For Linux, run: `xclip -sel clip < ~/.ssh/id_ed25519.pub`.

This looks more complicated to understand than opening the file in a text editor and copying its contents manually.

I've added the reference to Git Bash further down in the document.

**Comment by Ace0009** [comment]
Actually, the problem is that most of the students can’t find their key, which is why I thought providing the command line would be helpful. They can simply copy and paste it into the terminal, and that’s it and they only need to do it once. But the choice is yours :)

**Comment by sattlerc** [comment]
> Actually, the problem is that most of the students can’t find their key, which is why I thought providing the command line would be helpful.

How about we instead add more details on how they can find their key? They need to learn this anyway to make sense of this note:

> **Note**: If you use the Chalmers lab computers, you may experience a problem with git cloning. This is due to the following:
>
> - `ssh-keygen` puts the key in `.ssh` in your user folder on the C drive.
> - git looks for your key in `.ssh` in your Z drive.

Right now, we just say:

> your key is stored relative to your home directory in `.ssh/id_<something>.pub`

Maybe we can help them find this? Do you have a suggestion?

Regading:

> <sub>Note: Do not push unnecessary files; only push the edited file.
> `git add the-files-you-have-changed`) Replace the-files-you-have-changed with the file(s) name.
 
With our current whitelisting approach to `.gitignore`, it is already hard to add unnecessary files.

**Comment by Ace0009** [comment]
Oh, you're right, I forgot about the `.gitignore`. But maybe it should be updated? During the first study period, students pushed a lot of unrelated files, like runtime files that were automatically created. (I don't know how)

By the way, sorry for my late response. You're absolutely right about making the explanation more detailed so they can find their key. The issue is that the `.ssh` folder is hidden by default, and students need to un-hide it. We could teach them how to un-hide the folder, copy the key, and then hide it again. What do you think? I can write some instructions for it if you think it's a good idea.

**Comment by sattlerc** [comment]
> During the first study period, students pushed a lot of unrelated files, like runtime files that were automatically created. (I don't know how)

Can you link an example project?

> The issue is that the .ssh folder is hidden by default, and students need to un-hide it. We could teach them how to un-hide the folder, copy the key, and then hide it again. What do you think? I can write some instructions for it if you think it's a good idea.

I'm not familiar with Windows. Shouldn't there be an option to display hidden folders?

**Comment by Ace0009** [comment]
> I'm not familiar with Windows. Shouldn't there be an option to display hidden folders?

There is, but the problem is that the students don't know that `.ssh` is hidden. I assume most of them aren't even aware of hidden folders. Maybe we could just mention it ? Like how they can find it.

> Can you link an example project?

I'm not sure if you have access to the repositories from LP1, but if you do, you can check group 7 from TDA417. I know that macOS creates `.DS_Store` files, so I always add that to my `.gitignore`. While grading, I noticed some groups had pushed the `.DS_Store` file. They also pushed a folder named `.venv` that contains many Python packages, as well as a bin folder, etc. I assume these shouldn't have been pushed!

**Comment by sattlerc** [comment]
> There is, but the problem is that the students don't know that .ssh is hidden. I assume most of them aren't even aware of hidden folders. Maybe we could just mention it ? Like how they can find it.

Yes! I don't know Windows, do you think you could a sentence on how to find hidden folders?

> I'm not sure if you have access to the repositories from LP1, but if you do, you can check group 7 from TDA417. I know that macOS creates .DS_Store files, so I always add that to my .gitignore. While grading, I noticed some groups had pushed the .DS_Store file. They also pushed a folder named .venv that contains many Python packages, as well as a bin folder, etc. I assume these shouldn't have been pushed!

Thanks, I'll have a look later.

**Comment by Ace0009** [comment]
> Yes! I don't know Windows, do you think you could a sentence on how to find hidden folders?

Something like this ? 
"The `.ssh` folder is hidden by default. To make it visible on Windows, open File Explorer, click on the `view` tab, then `show` and check `hidden items`. Then go to the location where you saved your SSH key when it was generated, and you'll be able to see the `.ssh` folder. You can press `Command + Shift + . `on Mac and `Ctrl + H` on Linux to make hidden files visible. Don't forget the location where you generate the SSH key. "

**Comment by heatherleaf** [comment]
Thanks for your effort @Ace0009! 

I didn't get any notification about your PR, don't know why (since I'm the owner of this repo...), so I just happened to stumble upon it now.

Anyway, @hugjoh has also forked this repo and made some suggestions, see this commit: 2a36f1c7b1747874f53546b4068d8c5168743eb9

Both of you have done very nice work, I guess now it's up to me and @sattlerc to make some decisions. Thanks again!

**Comment by sattlerc** [comment]
> I'm not sure if you have access to the repositories from LP1, but if you do, you can check group 7 from TDA417. I know that macOS creates `.DS_Store` files, so I always add that to my `.gitignore`. While grading, I noticed some groups had pushed the `.DS_Store` file. They also pushed a folder named `.venv` that contains many Python packages, as well as a bin folder, etc. I assume these shouldn't have been pushed!

I guess you mean this? https://git.chalmers.se/courses/lp1-data-structures/2024/tda417/lab-2/lab2-group-7

It looks like the initial commit didn't add any `.gitignore` file. The problem branches were manually uploaded this time and it looks like hidden files were not added. That's on us.

**Comment by heatherleaf** [comment]
Thanks, I took some of your suggestions when I reorganised the tuturial in c149cfc6c7dcdabfb42c55fdcbb382fe3f569063

**Pull request closed without merging**
